# Generated by Django 6.0.6 on 2026-06-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
