# Generated by Django 6.0.6 on 2026-06-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_consultation_fee_doctor_is_emergency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_hours',
            field=models.CharField(default='9:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(default='MBBS', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='position',
            field=models.CharField(default='Senior Consultant', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(default=5, help_text='Years of experience'),
        ),
    ]
